config/routes.rb
Rails.application.routes.draw do
  resources :work_days

  resources :days

  resources :calenders

  resources :users

end

app/models/calender.rb
class Calender < ActiveRecord::Base
  has_many :days, :dependent => :destroy
end

app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
  before_action :set_calender, only: [:show, :edit, :update, :destroy]

  # GET /calenders
  # GET /calenders.json
  def index
    @calenders = Calender.all
    if @calenders.empty? or !@calenders.where(year: Time.now.strftime('%Y').to_i).size != 12
      new
    end

    @calenders = Calender.all
  end

  # GET /calenders/1
  # GET /calenders/1.json
  def show
  end

  # GET /calenders/new
  def new
    1.upto 12 do |month|
      @calender = Calender.new
      m = Time.local(Time.now.year, month, 1).strftime('%m')
      y = Time.local(Time.now.year, month, 1).strftime('%Y')

      next unless Calender.where(month: m, year: y).empty?

      @calender.month = m
      @calender.year  = y

      1.upto(Time.now.end_of_month.day) do |day|
        @calender.days << Day.new(name: day.to_i)
      end
      @calender.save
    end
  end

  # GET /calenders/1/edit
  def edit
  end

  # POST /calenders
  # POST /calenders.json
  def create
    @calender = Calender.new(calender_params)

    respond_to do |format|
      if @calender.save
        format.html { redirect_to @calender, notice: 'Calender was successfully created.' }
        format.json { render :show, status: :created, location: @calender }
      else
        format.html { render :new }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calenders/1
  # PATCH/PUT /calenders/1.json
  def update
    respond_to do |format|
      if @calender.update(calender_params)
        format.html { redirect_to @calender, notice: 'Calender was successfully updated.' }
        format.json { render :show, status: :ok, location: @calender }
      else
        format.html { render :edit }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calenders/1
  # DELETE /calenders/1.json
  def destroy
    @calender.destroy
    respond_to do |format|
      format.html { redirect_to calenders_url, notice: 'Calender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calender
      @calender = Calender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calender_params
      params.require(:calender).permit(:month)
    end
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/views/calenders/_form.html.erb
<%= form_for(@calender) do |f| %>
  <% if @calender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calender.errors.count, "error") %> prohibited this calender from being saved:</h2>

      <ul>
      <% @calender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calenders/edit.html.erb
<h1>Editing calender</h1>

<%= render 'form' %>

<%= link_to 'Show', @calender %> |
<%= link_to 'Back', calenders_path %>

app/views/calenders/index.html.erb
<h1>Listing calenders</h1>

<table>
  <thead>
    <tr>
      <th>Month</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calenders.each do |calender| %>
      <tr>
        <td><%= calender.month %></td>
        <td><%= link_to 'Show', calender %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calender', new_calender_path %>

app/views/calenders/new.html.erb
<h1>New calender</h1>

<%= render 'form' %>

<%= link_to 'Back', calenders_path %>

app/views/calenders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Month:</strong>
  <%= Time.local(@calender.year, @calender.month, 1).strftime('%B') %>

<table>
  <thead>
  <tr>
    <th>Day</th>
    <th>Entries</th>
    <th>Diff</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @calender.days.each do |day| %>
      <tr>
        <% time = Time.local(@calender.year, @calender.month, day.name)%>
        <td><%= day.name %>/<%= @calender.month%><br/> <%= time.strftime('%a')%></td>
        <%total = 0%>
        <%day.work_days.each do |entry|%>
            <%interval = entry.lunch.hour + entry.lunch.min / 60.0%>
            <%total += TimeDifference.between(entry.in_hour, entry.out_hour).in_hours - interval%>
        <%end%>
        <td><%= day.work_days.size%></td>
        <td><%= total%> hour(s)</td>

        <td><%= link_to 'New entry', controller: 'work_days', action: 'index',
                                        day: day.name, month: @calender.month, year: @calender.year%></td>
      </tr>
  <% end %>
  </tbody>
</table>

</p>

<%= link_to 'Back', calenders_path %>