config/routes.rb
Rails.application.routes.draw do
  resources :work_days

  resources :days

  resources :calenders

  resources :users

end

app/models/work_day.rb
class WorkDay < ActiveRecord::Base
end

app/controllers/work_days_controller.rb
class WorkDaysController < ApplicationController
  before_action :set_work_day, only: [:show, :edit, :update, :destroy]

  # GET /work_days
  # GET /work_days.json
  def index
    @year  = params[:year]
    @month = params[:month]
    @day   = params[:day]
    calender = Calender.where(year: @year, month: @month).first
    day = calender.days.where(name: @day)
    @work_days = day.first.work_days
  end

  # GET /work_days/1
  # GET /work_days/1.json
  def show
  end

  # GET /work_days/new
  def new
    @year  = params[:year]
    @month = params[:month]
    @day   = params[:day]
    @work_day = WorkDay.new
  end

  # GET /work_days/1/edit
  def edit
    @year  = params[:year]
    @month = params[:month]
    @day   = params[:day]
  end

  # POST /work_days
  # POST /work_days.json
  def create
    @year  = params[:year]
    @month = params[:month]
    @day   = params[:day]

    calender = Calender.where(year: @year, month: @month).first
    day = calender.days.where(name: @day)

    @work_day = WorkDay.new(work_day_params)

    respond_to do |format|
      if @work_day.save
        day.first.work_days << @work_day
        day.first.save
        format.html { redirect_to controller: 'calenders', action: 'show', id: calender.id,
                                  notice: 'Work day was successfully created.'}
      else
        format.html { redirect_to controller: 'days', action: 'index' }
      end
    end
  end

  # PATCH/PUT /work_days/1
  # PATCH/PUT /work_days/1.json
  def update
    @year  = params[:year]
    @month = params[:month]
    @day   = params[:day]

    calender = Calender.where(year: @year, month: @month).first
    day = calender.days.where(name: @day)

    respond_to do |format|
      if @work_day.update(work_day_params)
        format.html { redirect_to controller: 'calenders', action: 'show', id: calender.id,
                                  notice: 'Work day was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_day }
      else
        format.html { render :edit }
        format.json { render json: @work_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_days/1
  # DELETE /work_days/1.json
  def destroy
    day_id      = @work_day.day_id
    calender_id = Day.find(day_id).calender_id

    @work_day.destroy
    respond_to do |format|
      format.html { redirect_to controller: 'calenders', action: 'show', id: calender_id,
                                notice: 'Work day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_day
      @work_day = WorkDay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_day_params
      params.require(:work_day).permit(:in_hour, :out_hour, :lunch)
    end
end

app/helpers/work_days_helper.rb
module WorkDaysHelper
end

app/views/work_days/_form.html.erb
<%if method_mode.nil?%>
    <%form = work_days_path(day: @day, month: @month, year: @year)%>
<%else%>
    <%form = work_day_path(day: @day, month: @month, year: @year)%>
<%end%>
<%= form_for(@work_day, url: form) do |f|%>
  <% if @work_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_day.errors.count, 'error') %> prohibited this work_day from being saved:</h2>

      <ul>
      <% @work_day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :in_hour %><br>
    <%= f.time_select :in_hour %>
  </div>
  <div class="field">
    <%= f.label :out_hour %><br>
    <%= f.time_select :out_hour %>
  </div>
  <div class="field">
    <%= f.label :lunch %><br>
    <%= f.time_select :lunch, {:default => {:hour => '1', :minute => '0'}} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_days/edit.html.erb
<h1>Editing work_day</h1>

<%= render partial: 'form', locals: {method_mode: :patch} %>

<%= link_to 'Show', @work_day %> |
<%= link_to 'Back', work_days_path %>

app/views/work_days/index.html.erb
<h1>Listing work_days</h1>

<%= @day%>/<%= @month%>/<%= @year%>

<table>
  <thead>
    <tr>
      <th>In hour</th>
      <th>Out hour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_days.each do |work_day| %>
      <tr>
        <td><%= work_day.in_hour.strftime('%H:%M') %></td>
        <td><%= work_day.out_hour.strftime('%H:%M') %></td>
        <td><%= link_to 'Edit', edit_work_day_path(work_day, day: @day, month: @month, year: @year) %></td>
        <td><%= link_to 'Destroy', work_day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work day', controller: 'work_days', action: 'new', day: @day, month: @month, year: @year %>

app/views/work_days/new.html.erb
<h1>New work_day</h1>

<%= render partial: 'form', locals: {method_mode: :create} %>

<%= link_to 'Back', work_days_path %>

app/views/work_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>In hour:</strong>
  <%= @work_day.in_hour.strftime('%H:%M') %>
</p>

<p>
  <strong>Out hour:</strong>
  <%= @work_day.out_hour.strftime('%H:%M') %>
</p>

<p>
  <strong>Lunch:</strong>
  <%= @work_day.lunch.strftime('%H:%M') %>
</p>

<%= link_to 'Edit', edit_work_day_path %> |
<%= link_to 'Back', controller: 'work_days', action: 'index', day: @day, month: @month, year: @year %>